builds:
  - id: dot
    goarch:
      - arm64
      - amd64
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser -X main.treeState={{ .IsGitDirty }}

archives:
  - format: binary
    name_template: "{{.Binary}}-{{.Os}}-{{.Arch}}-{{.Version}}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Build process updates"
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

release:
  footer: |
    **Full Changelog**: https://github.com/gszr/dot/compare/{{ .PreviousTag }}...{{ .Tag }}
  github:
    owner: gszr
    name: dot
  target_commitish: "{{ .Commit }}"

